require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - 'Struct.new'
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/benchin/data_tree/config/*.rb'

Naming/UncommunicativeMethodParamName:
  Exclude:
    - '**/*.md'

Style/MixinUsage:
  Exclude:
    - '**/*.md'

Lint/UnusedMethodArgument:
  Exclude:
    - '**/*.md'

Lint/UnusedBlockArgument:
  Exclude:
    - '**/*.md'
