name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 2 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5.x
          - 2.6.x
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Bundler
        run: gem install bundler
      - name: Install Hunspell
        run: sudo apt-get install hunspell
      - name: Install Deps
        run: bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop
      - name: Reek
        run: bundle exec reek
      - name: RSpec
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bundle exec rspec
      - name: Markdown Linter (docs)
        run: bundle exec mdl README.md
      - name: Spelling Check (docs & code)
        run: bundle exec forspell
